version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: medzk-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  backend:
    build: ./backend
    container_name: medzk-backend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongodb:27017/medzk
      - JWT_SECRET=medzk_production_secret_key_99
      - RPC_URL=http://localhost:8545
      - GATEWAY_PRIVATE_KEY=0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d
      - ISSUER_KEY_SECRET=000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f
    depends_on:
      - mongodb
    restart: always

volumes:
  mongo-data:
